/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_rocketmq_remoting_vtoa_VpcTunnelUtils */

#ifndef _Included_org_apache_rocketmq_remoting_vtoa_VpcTunnelUtils
#define _Included_org_apache_rocketmq_remoting_vtoa_VpcTunnelUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_rocketmq_remoting_vtoa_VpcTunnelUtils
 * Method:    getvip
 * Signature: (ILorg/apache/rocketmq/remoting/vtoa/Vtoa;)I
 */
JNIEXPORT jint JNICALL Java_org_apache_rocketmq_remoting_vtoa_VpcTunnelUtils_getvip
  (JNIEnv *, jclass, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
